# Generated by Django 2.2 on 2020-07-07 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('homeowner', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('prior_insurance', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('limit', models.CharField(blank=True, choices=[('Minimum', '$15,000/$30,000/$10,000 (Minimum)'), ('Good', '$25,000/$50,000/$25,000 (Good)'), ('Better', '$50,000/$100,000/$25,000 (Better)'), ('Best', '$100,000/$300,000/$50,000 (Better)'), ('Superior', '$100,000/$300,000/$50,000 (Superior)')], max_length=20, null=True)),
                ('uninsured_cov', models.CharField(blank=True, choices=[('Decline Coverage', 'Decline Coverage'), ('Minimum', '$15,000/$30,000/$3,500 (Minimum)')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='QuoteShell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(blank=True, choices=[('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Toyota', 'Toyota'), ('Honda', 'Honda')], max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('use_type', models.CharField(blank=True, choices=[('Commute', 'Commute'), ('Pleasure', 'Pleasure'), ('Business', 'Business'), ('Uber/Lyft', 'Uber/Lyft')], max_length=20, null=True)),
                ('work_miles', models.CharField(blank=True, choices=[('05', '0-5'), ('510', '5-10'), ('1015', '10-15'), ('1520', '15-20'), ('2030', '20-30'), ('30g', '30+')], max_length=10, null=True)),
                ('year_miles', models.CharField(blank=True, choices=[('5000', '5,000'), ('12000', '12,000'), ('15000', '15,000'), ('25000', '25,000+')], max_length=20, null=True)),
                ('coverage_type', models.CharField(blank=True, choices=[('Full Coverage', 'Full Coverage'), ('Liability Only', 'Liability Only')], max_length=20, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='quotes.Quote')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_shell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.QuoteShell'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Nonbinary', 'Nonbinary')], max_length=12, null=True)),
                ('martial', models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Domestic Partnership', 'Domestic Partnership')], max_length=20, null=True)),
                ('age_license', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, choices=[('Administrative Clerical', 'Administrative Clerical'), ('Architect', 'Architect'), ('Business Owner', 'Business Owner'), ('Certified Public Accountant', 'Certified Public Accountant'), ('Clergy', 'Clergy'), ('Construction Trades', 'Construction Trades')], max_length=100, null=True)),
                ('license_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Permit', 'Permit'), ('Expired', 'Expired'), ('Suspened', 'Suspened'), ('Foreign', 'Foreign')], max_length=100, null=True)),
                ('sr22', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('dui', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('prev_lic_status', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('incident_status3', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='quotes.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('street2', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('residence_type', models.CharField(blank=True, choices=[('Single Family Home', 'Single Family Home'), ('Condominuim', 'Condominuim'), ('Mobile Home', 'Mobile Home'), ('Apartment', 'Apartment')], max_length=30, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='quotes.Quote')),
            ],
        ),
    ]
