# Generated by Django 2.2 on 2020-06-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
    ]
