# Generated by Django 2.2 on 2020-07-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='military_discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='professional_discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='student_discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='limit',
            field=models.CharField(blank=True, choices=[('Minimum', '$15,000/$30,000/$10,000 (Minimum)'), ('Good', '$25,000/$50,000/$25,000 (Good)'), ('Better', '$50,000/$100,000/$25,000 (Better)'), ('Best', '$100,000/$300,000/$50,000 (Best)'), ('Superior', '$100,000/$300,000/$50,000 (Superior)')], max_length=20, null=True),
        ),
    ]
