# Generated by Django 2.2 on 2020-07-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20200707_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteshell',
            name='ip',
        ),
        migrations.AddField(
            model_name='quote',
            name='ip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
