# Generated by Django 2.2 on 2020-07-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200709_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='martial',
            new_name='marital',
        ),
    ]
