# Generated by Django 2.2 on 2020-06-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200625_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='gender',
        ),
        migrations.AlterField(
            model_name='driver',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
