# Generated by Django 2.2 on 2020-06-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200630_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='coverage_type',
            field=models.CharField(choices=[('FC', 'Full Coverage'), ('LO', 'Liability Only')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Toyota', 'Toyota'), ('Honda', 'Honda')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='use_type',
            field=models.CharField(choices=[('CO', 'Commute'), ('PL', 'Pleasure'), ('BU', 'Business'), ('UL', 'Uber/Lyft')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='work_miles',
            field=models.CharField(choices=[('05', '0-5'), ('510', '5-10'), ('1015', '10-15'), ('1520', '15-20'), ('2030', '20-30'), ('30g', '30+')], default='', max_length=10, null=True),
        ),
    ]
