# Generated by Django 2.2 on 2020-07-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20200630_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='use_type',
            field=models.CharField(choices=[('Commute', 'Commute'), ('Pleasure', 'Pleasure'), ('Business', 'Business'), ('Uber/Lyft', 'Uber/Lyft')], default='', max_length=20, null=True),
        ),
    ]
